---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Mickaël Canouil's Analysis Scripts Templates

<!-- badges: start -->
[![Lifecycle:
experimental](https://img.shields.io/badge/lifecycle-experimental-orange.svg)](https://www.tidyverse.org/lifecycle/#experimental)
[![GitHub
tag](https://img.shields.io/github/tag/mcanouil/analysis_templates.svg?label=latest%20tag&include_prereleases)](https://github.com/mcanouil/analysis_templates)
<!-- badges: end -->

Script templates to work with omics datasets.

```{r, echo = FALSE, results = "asis"}
dt <- data.table::data.table(
  file = setdiff(sort(list.files(path = here::here(), pattern = ".R", recursive = TRUE)), "README.Rmd")
)[
  j = root := data.table::tstrsplit(x = file, "/", keep = 1)
][
  !grepl("assets", file)
][
  j = list(
    list_scripts = c(
      sprintf("\n## %s\n", root),
      if (grepl("Rmarkdown", root)) {
        "\nNote: `assets` directory from [github.com/umr1283/xaringan-template](https://github.com/umr1283/xaringan-template) is required!\n\n"
      },
      if (filedir != root) sprintf("\n### %s\n", filedir),
      sprintf("  * [%s](%s)\n", basename(file), file)
    )
  ),
  by = list(root, filedir = dirname(file))
][
  order(factor(root, levels = c("R", "R/scripts", "R/targets", "R/functions")))
]

cat(dt[["list_scripts"]][!duplicated(dt[["list_scripts"]])], sep = "")
```
